"use client";
import React, { useEffect, useState } from "react";
import DecodeText from "../typography/DecodeText";

export default function GlassCard() {
  return (
    <div className=" h-full flex justify-center items-start p-16 text-white overflow-hidden">
      {/* Glass Card */}
      <div
        className={`
          relative z-20 w-[640px] mx-auto rounded-[0.7rem] overflow-hidden
          [clip-path:polygon(32px_0,100%_0,100%_calc(100%-32px),calc(100%-32px)_100%,0_100%,0_32px)]
          border border-white/20 border-t-white/40 border-l-white/40
          bg-[rgba(40,40,60,0.25)] backdrop-blur-[12px] [backdrop-saturate:160%]
          shadow-[0_8px_24px_rgba(0,0,0,0.4),inset_0_1px_8px_rgba(255,255,255,0.1)]
          transition-transform duration-300 ease-in-out
          hover:-translate-y-1.5 hover:scale-[1.02] hover:shadow-[0_28px_70px_rgba(0,0,0,0.65)] hover:brightness-110
          before:content-[''] before:absolute before:top-[-90%] before:left-[-75%] before:w-1/2 before:h-[260%]
          before:bg-[linear-gradient(120deg,transparent_0%,rgba(255,255,255,0.55)_50%,transparent_100%)]
          before:[transform:skewX(-25deg)] before:transition-[left] before:duration-[650ms] before:ease-[cubic-bezier(0.22,1,0.36,1)]
          before:z-20 before:pointer-events-none
          hover:before:left-[140%]
          after:content-[''] after:absolute after:top-[-50%] after:left-[-50%] after:w-[200%] after:h-[200%]
          after:bg-[linear-gradient(120deg,rgba(255,255,255,0.15)_0%,rgba(255,255,255,0.05)_40%,transparent_60%)]
          after:rotate-[25deg] after:mix-blend-screen after:pointer-events-none after:z-10
          max-[480px]:w-[calc(100%-40px)]
        `}
      >
        <div className="relative z-30 flex flex-col p-4 w-[92%] mx-auto">
          <h2 className="mt-2 mb-1 text-white text-lg font-semibold">
            Glassmorphism Card
          </h2>
          <p className="my-1 text-[#cdbbef] text-[0.95rem]">
            <DecodeText
              text="ur project contains lock files generated by tools other than Yarn."
              interval={200}
            />
          </p>
          <p className="my-1 text-[#cdbbef] text-[0.95rem]">
            ur project contains lock files generated by tools other than Yarn.
          </p>
          <p className="my-1 text-[#cdbbef] text-[0.95rem]">
            ur project contains lock files generated by tools other than Yarn.
          </p>
        </div>
      </div>
    </div>
  );
}
