"use client";
import React from "react";
import "@/styles/cards.scss";
import Image from "next/image";
import DecodeText from "../typography/DecodeText";

export default function GlassCard() {
  return (
    <div className="glass-page">
      {/* Long background text nằm phía sau card */}
      <div className="background-text">
        THIS IS A LONG BACKGROUND TEXT — LOOK HOW IT PASSES UNDER THE GLASS CARD
        — ONLY THE PART UNDER THE CARD GETS BLURRED — THIS IS THE FROSTED GLASS
        EFFECT.
      </div>

      {/* Card nằm trên, có backdrop-filter để blur phần background phía sau */}
      <div className="nft">
        <div className="main">
          {/* <Image
            className="tokenImage"
            src="https://picsum.photos/400/250"
            alt="demo"
            width={400}
            height={250}
          /> */}
          <h2>Glassmorphism Card</h2>
          <p className="description">
            <DecodeText
              text="ur project contains lock files generated by tools other than Yarn."
              interval={200}
            />
          </p>
          <p className="description">
            ur project contains lock files generated by tools other than Yarn.
          </p>
          <p className="description">
            ur project contains lock files generated by tools other than Yarn.
          </p>
        </div>
      </div>
    </div>
  );
}
